// <auto-generated>
using DBD.SaveGame;
using UnityEngine;

public partial class DataSave
{
	public bool IsSfxOn
	{
		get => isSfxOn.Value;
		set => isSfxOn.Value = value;
	}

	public bool IsMusicOn
	{
		get => isMusicOn.Value;
		set => isMusicOn.Value = value;
	}

	public bool IsVibrateOn
	{
		get => isVibrateOn.Value;
		set => isVibrateOn.Value = value;
	}

	public SaveList<SaveItemCard> SaveItemCards
	{
		get => saveItemCards;
		set => saveItemCards = value;
	}
}
